version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE:  api_seguranca
      MYSQL_USER: davi
      MYSQL_PASSWORD: 123456
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
    
